### ISSUE TITLE
some suggets to recognize digits with device camera from electric meter?

### ISSUE THREAD

**Issue by Barceloch** [spidgorny/energy-monitor#4]
---

**Comment by spidgorny** [comment]
My code is using OpenCV, which is quite large (IMHO).
I would create a backend web-service for detecting numbers from images instead of running it inside the Android.
This would require a network connection to work, but this is usually not a problem for Android. This way you also don't need to bundle big libraries in your APK.

**Comment by Barceloch** [comment]
Thanks for your answer, I understand, the problem y that I am from cuba and
the internet connection is limited, for that I need a solution offline
